### ISSUE TITLE
error "nested"

### ISSUE THREAD

**Issue by lengagne** [stack-of-tasks/soth#11]
Hi,

I used soth on Ubuntu 14. Now I would like to use it on Ubuntu 16 but I have the foloowing error, and I cannot find a solution, can you help me ?

[  9%] Building CXX object src/CMakeFiles/soth.dir/BaseY.cpp.o
cd ~/devel/soth/build/src && /usr/bin/c++   -DHAVE_SYS_TIME_H -Dsoth_EXPORTS -I~/devel/soth/build -I~/devel/soth/build/include -I~/devel/soth/include -isystem /usr/include/eigen3  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -fPIC   -fpermissive -o CMakeFiles/soth.dir/BaseY.cpp.o -c ~/devel/soth/src/BaseY.cpp
In file included from ~/devel/soth/build/include/soth/Givens.hpp:7:0,
                 from ~/devel/soth/build/include/soth/BaseY.hpp:8,
                 from ~/devel/soth/src/BaseY.cpp:1:
~/devel/soth/build/include/soth/SubMatrix.hpp:32:24: error: expected nested-name-specifier before ‘nested’
       typedef typename nested<MatrixType>::type MatrixTypeNested;
                        ^
~/devel/soth/build/include/soth/SubMatrix.hpp:32:24: error: expected ‘;’ at end of member declaration
~/devel/soth/build/include/soth/SubMatrix.hpp:32:30: error: expected unqualified-id before ‘<’ token
       typedef typename nested<MatrixType>::type MatrixTypeNested;
                              ^
~/devel/soth/build/include/soth/SubMatrix.hpp:33:41: error: ‘MatrixTypeNested’ was not declared in this scope
       typedef typename remove_reference<MatrixTypeNested>::type _MatrixTypeNested;
                                         ^
~/devel/soth/build/include/soth/SubMatrix.hpp:33:57: error: template argument 1 is invalid
       typedef typename remove_reference<MatrixTypeNested>::type _MatrixTypeNested;
                                                         ^
~/devel/soth/build/include/soth/SubMatrix.hpp:40:11: error: ‘_MatrixTypeNested’ is not a class or namespace
  Flags = (_MatrixTypeNested::Flags & HereditaryBits) | ei_compute_lvalue_bit<_MatrixTypeNested>::ret,
           ^
~/devel/soth/build/include/soth/SubMatrix.hpp: In instantiation of ‘struct Eigen::ei_compute_lvalue_bit<int>’:
~/devel/soth/build/include/soth/SubMatrix.hpp:40:96:   required from here
~/devel/soth/build/include/soth/SubMatrix.hpp:21:36: error: ‘Flags’ is not a member of ‘int’
     enum {ret = (MatrixType::Flags & (DirectAccessBit | LvalueBit))?LvalueBit:0};
                                    ^
~/devel/soth/build/include/soth/SubMatrix.hpp:41:18: error: ‘_MatrixTypeNested’ is not a class or namespace
  CoeffReadCost = _MatrixTypeNested::CoeffReadCost //Todo : check that
                  ^
~/devel/soth/build/include/soth/SubMatrix.hpp:639:24: error: expected nested-name-specifier before ‘nested’
       typedef typename nested<MatrixType1>::type MatrixTypeNested;
                        ^
~/devel/soth/build/include/soth/SubMatrix.hpp:639:24: error: expected ‘;’ at end of member declaration
~/devel/soth/build/include/soth/SubMatrix.hpp:639:30: error: expected unqualified-id before ‘<’ token
       typedef typename nested<MatrixType1>::type MatrixTypeNested;
                              ^
~/devel/soth/build/include/soth/SubMatrix.hpp:640:41: error: ‘MatrixTypeNested’ was not declared in this scope
       typedef typename remove_reference<MatrixTypeNested>::type _MatrixTypeNested;
                                         ^
~/devel/soth/build/include/soth/SubMatrix.hpp:640:57: error: template argument 1 is invalid
       typedef typename remove_reference<MatrixTypeNested>::type _MatrixTypeNested;
                                                         ^
~/devel/soth/build/include/soth/SubMatrix.hpp:647:11: error: ‘_MatrixTypeNested’ is not a class or namespace
  Flags = (_MatrixTypeNested::Flags & HereditaryBits) | ei_compute_lvalue_bit<_MatrixTypeNested>::ret,
           ^
~/devel/soth/build/include/soth/SubMatrix.hpp:648:18: error: ‘_MatrixTypeNested’ is not a class or namespace
  CoeffReadCost = _MatrixTypeNested::CoeffReadCost //Todo : check that
                  ^
src/CMakeFiles/soth.dir/build.make:137 : la recette pour la cible « src/CMakeFiles/soth.dir/BaseY.cpp.o » a échouée

**Comment by eirtech** [comment]
Hi,
I have the same problem. Did you solve it @lengagne ?

**Comment by lengagne** [comment]
It seems that I do not have this issue when I compile soth with eigen 3.2.10 (Default package version in Ubuntu 16 is eigen 3.2.96). 

I find it this morning on a virtual machine, I will test it tomorrow on actual (non virtual) Ubuntu Mate 16.04. I will let you know the results (I hope that will be the same ;) ). Feel free to ask me again if I forgot to give you some news.

**Comment by olivier-stasse** [comment]
Hi @lengagne, @eirtech,
Sorry about our slow response. 
We started to install the overall infra-structure to test our packages on 16.04 LTS. The only problem for now is that all of our robot are still on 14.04 LTS. I will to give it a shoot during December, but right now my stack of tasks ;) is in overflow mode... 

Thanks again for your interest.
Olivier.

**Comment by eirtech** [comment]
@lengagne 
Yes. I have eigen 3.3. So, after using version 3.2 with this package, the issue was solved.

**Comment by lengagne** [comment]
The same for me, I installed eigen 3.2.10 and there is no issue anymore.

**Comment by jmirabel** [comment]
What happens if you change `nested` by `ref_selector` in `SubMatrix.hpp` and use Eigen 3.3 ?
You may also try `nested_eval` instead of `nested`

**Comment by eirtech** [comment]
@jmirabel 
ref_selector is suitable term to use. But this nested is not the only issue and there are some other things which shoud be changed.

**Comment by olivier-stasse** [comment]
Hi @jmirabel my current state on a fix to this problem is available [here](https://github.com/olivier-stasse/soth/tree/topic/xenial)

**Comment by olivier-stasse** [comment]
Dear @lengagne and @eirtech Joseph proposed a fix which is passing the unit tests.
We did not check the code more than that for now.
Let me know if it works for you, I will closed the issue with respect to the compilation issue.
FYI the head of master is now compatible with xenial.

Best,
Olivier.
